---
- hosts: demo
  become: yes
  tasks:
   - name: install git
     apt: name=git state=present
   - name: install apache2
     apt: name=apache2 state=present
   - name: started the apache2
     service: name=apache2 state=started

